services:
  # Speech Processing Server (uses your existing Ollama)
  speech-server:
    build: ./speech-server
    container_name: echo-speech
    ports:
      - "5001:8080"
    volumes:
      - ./models:/app/models
      - ./audio_cache:/app/audio_cache
    environment:
      - OLLAMA_URL=http://192.168.68.55:11434
      - STT_MODEL=base
      - DEVICE=cpu
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: echo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: